### ISSUE TITLE
ESP Stuck on Sudden Internet Failure

### ISSUE THREAD

**Issue by subhasis-manna** [StorageB/Google-Sheets-Logging#3]
Hi, 
Thank for the great library. I am facing a minor issue while upload the sensor data to google sheet.
In case of sudden internet failure ESP got Stuck in Following lines of Program.

Part of Code.. 
 ```
// Publish data to Google Sheets
  Serial.println("Publishing data...");
  Serial.println(payload);
  if(client->POST(url, host, payload)){ 
    // do stuff here if publish was successful
  }
  else{
    // do stuff here if publish was not successful
    Serial.println("Error while connecting");
  }
```

Serial Monitor Display 
17:05:51.223 -> Publishing data...
17:05:51.223 -> {"command": "insert_row", "sheet_name": "Sheet1", "values": "28.00,30.00,14,SCAQI211101"}

Is there any way to set any time out for this command
 ```
 if(client->POST(url, host, payload)){ 
    // do stuff here if publish was successful
  }

```
Any Assistance will be helpful.

**Comment by StorageB** [comment]
Hello @subhasis-manna 

The request to send and receive data from Google Sheets is handled by the HTTPSRedirect library: 
https://github.com/electronicsguy/HTTPSRedirect

Any sort of modification to how the request is carried out would have to be done within that library.

**Comment by subhasis-manna** [comment]
Thank You..
